### PR TITLE
feat: add virtual machine disks

### PR DESCRIPTION
**Pull request by Ikke**
Netbox 3.7 added [support for virtual machine disks][0], so add the necessary code the support this.

The client code has been copied from virtual machines, the models from virtual chassis.

[0]:https://docs.netbox.dev/en/stable/release-notes/version-3.7/#virtual-machine-disks-8356

### CODE REVIEW

**Comment by Ikke** [comment]
I've marked this as draft as I have not tested the code yet.

**Comment by fbreckle** [comment]
Hi,

when impleneting completely new models and their APIs, please update the postprocessor or the swagger.json and generate accordingly.

Also note that I am currently implementing the new vpn stuff in https://github.com/fbreckle/go-netbox/tree/feature/vpn , so conflicts may arise.

**Comment by Ikke** [comment]
Ok, I must have misunderstood the readme then:

> In conclusion, at the time of writing this, NetBox 3.5 is out quite some time already with NetBox 3.6 around the corner, so I decided that the show must go on and manual adjustments to this client are now the fastest way to allow the terraform provider to support newer NetBox versions.

**Comment by fbreckle** [comment]
Yes, I figured that youve read that and then did the changes. I can just merge this if you need it right now, if you do not want to adjust the swagger stuff accordingly.

Im actually really torn on how to proceed with this library. I didnt expect them to keep adding new models so fast. I find adjusting the client via swagger "manually" extremely annoying as well. This VPN alone is like five whole new models again. 

But changing to the openapi3 go-netbox requires a complete rewrite of the provider, which is also pretty much out of scope for my current time. Just venting. :\

**Comment by Ikke** [comment]
> I can just merge this if you need it right now, if you do not want to adjust the swagger stuff accordingly.

I'll first try to get the models / client updated  using the generator, and I also wanted to at least verify it through terraform-provider-netbox.

>  which is also pretty much out of scope for my current time. Just venting. :\

No worries, I completely understand

**Comment by fbreckle** [comment]
We just got an issue about this feature in the provider and it reminded me of this PR. Any news?

No pressure, I just don't like duplicate work being done.

**Comment by Ikke** [comment]
I'm planning on finishing it tomorrow. I have managed to update swagger.json and use the generator, so only thing left is confirming everything is working as expected.

**Comment by Ikke** [comment]
@fbreckle I think this is ready now.

**Pull request merged**
