### PR TITLE
Allow empty coordinates

### PR DESCRIPTION
**Pull request by haipersuccor02**
This PR is part of this change https://github.com/fbreckle/go-netbox/pull/35/files . We just run the `make generate` to reflect changes

### CODE REVIEW

**Comment by fbreckle** [comment]
oh ok, I didnt even check the go file that was changed in the last PR. I just assumed it reflects the changes in the preprocess/swagger file :D my bad

**Comment by haipersuccor02** [comment]
No worries, thank you for your help on merging it :)

**Comment by haipersuccor02** [comment]
Hi @fbreckle , it seems that the changes are not yet being reflected, we need the latest go-netbox in the terraform-provider, how can we use it?

**Comment by fbreckle** [comment]
Just use go get `github.com/fbreckle/go-netbox@<commit id>`. Current master is `e4c3e860c1538cb8f933887ecf33192d2a9376f4`

**Pull request merged**
